husori/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^login/', include('login.urls')),
]

login/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = "login"

urlpatterns = [

    url(r'^$',views.register,name='register'),
    url(r'^(?P<status>[0-9]+)/$',views.dashboard,name='dashboard'),
    url(r'^logout/$',views.logout,name='logout'),

]

login/models.py
from django.db import models
from django.core.urlresolvers import reverse

class profiles(models.Model):
    username=models.CharField(max_length=250,default='ok')
    password= models.CharField(max_length=50,default='k')
    code1= models.CharField(max_length=250,null=True)
    code2= models.CharField(max_length=250,null=True)
    code3= models.CharField(max_length=250,null=True)
    code4= models.CharField(max_length=250,null=True)
    code5= models.CharField(max_length=250,null=True)
    code6= models.CharField(max_length=250,null=True)
    status= models.IntegerField(default=1)
    filled =models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('login:dashboard', kwargs= {'pk':self.pk})

    def __str__(self):
       return self.username + ' - ' + self.password

login/forms.py
from django import forms

class AlbumRegister(forms.Form):
    username= forms.CharField(max_length=250)
    password= forms.CharField(max_length=50)

class Code1(forms.Form):
    code1 = forms.CharField(max_length=250)

class Code2(forms.Form):
    code2 = forms.CharField(max_length=250)

class Code3(forms.Form):
    code3 = forms.CharField(max_length=250)

class Code4(forms.Form):
    code4 = forms.CharField(max_length=250)

class Code5(forms.Form):
    code5 = forms.CharField(max_length=250)

class Code6(forms.Form):
    code6 = forms.CharField(max_length=250)

login/views.py
from django.shortcuts import render
from .models import profiles
from .forms import AlbumRegister,Code1, Code2, Code3, Code4, Code5, Code6

def register(request):
    all_profiles = profiles.objects.all()
    username = ""
    password = ""
    context = {

    }
    if request.method == 'POST':
        myForm = AlbumRegister(request.POST)
        if myForm.is_valid():
            username = myForm.cleaned_data['username']
            password = myForm.cleaned_data['password']
            flag = 0
            dbuser = profiles()
            for i in range(len(all_profiles)):
                if all_profiles[i].username == username and all_profiles[i].password == password:
                    dbuser = profiles.objects.filter(password=password)
                    flag = 1
            request.session['username'] = username
            if flag == 1:
                context = {
                    'user': dbuser[0]
                }
                if dbuser[0].filled:
                    return render(request, 'login/profileview.html', context)
                else:
                    context3 = {
                        'status': dbuser[0].status
                    }
                    return render(request,'login/'+ str(dbuser[0].status) +'.html', context3)
            else:
                new_profile = profiles()
                new_profile.username = username
                new_profile.password = password
                new_profile.save()

                context={'new_profile':new_profile}
                return render(request,'login/dashboard.html',context)
    else:
        myForm = AlbumRegister(request.GET)
        return render(request, 'login/index.html')

def dashboard(request,status):
    code1=""
    code2 = ""
    code3 = ""
    code4 = ""
    code5 = ""
    code6 = ""
    context2 = {

    }
    dbuser = profiles()
    if request.method == 'POST':
        if request.session.has_key('username'):
            username = request.session['username']
            dbuser = profiles.objects.filter(username=username)
            context2 = {
                'status': status
            }
            user = profiles.objects.get(username=username)

            if user.status == 1:
                MyForm2 = Code1(request.POST)
                if MyForm2.is_valid():
                    code1 = MyForm2.cleaned_data['code1']
                    print("yo")
                    user.code1 = code1
            if user.status == 2:
                MyForm3 = Code2(request.POST)
                if MyForm3.is_valid():
                    code2 = MyForm3.cleaned_data['code2']
                    user.code2 = code2
            if user.status == 3:
                MyForm4 = Code3(request.POST)
                if MyForm4.is_valid():
                    code3 = MyForm4.cleaned_data['code3']
                    user.code3 = code3
            if user.status == 4:
                MyForm5 = Code4(request.POST)
                if MyForm5.is_valid():
                    code4 = MyForm5.cleaned_data['code4']
                    user.code4 = code4
            if user.status == 5:
                MyForm6 = Code5(request.POST)
                if MyForm6.is_valid():
                    code5 = MyForm6.cleaned_data['code5']
                    user.code5 = code5
            if user.status == 6:
                MyForm7 = Code6(request.POST)
                if MyForm7.is_valid():
                    code6 = MyForm7.cleaned_data['code6']
                    user.code6 = code6
            user.status += 1
            user.save()
            return render(request, 'login/'+ str(user.status) +'.html',context2)
    else:
        if request.method == 'GET':
            if request.session.has_key('username'):
                username = request.session['username']
                user = profiles.objects.get(username=username)
                context2 = {
                    'status': status
                }
                if user.status == 1:
                    MyForm2 = Code1(request.GET)
                if user.status == 2:
                    MyForm2 = Code2(request.GET)
                if user.status == 3:
                    MyForm2 = Code3(request.GET)
                if user.status == 4:
                    MyForm2 = Code4(request.GET)
                if user.status == 5:
                    MyForm2 = Code5(request.GET)
                if user.status == 6:
                    MyForm2 = Code6(request.GET)
                return render(request,'login/'+ str(user.status) +'.html',context2)

def logout(request):
    try:
        del request.session['username']
    except:
        pass

    return render(request,'login/index.html',{})

login/templates/login/1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Code1</title>
</head>
<body>
    <form method="post" action="{% url 'login:dashboard' status %}" >
        {% csrf_token %}
        code1: <input type="text" name="code1">
        <br>
        <button type="submit">Next</button>

    </form>
</body>
</html>

login/templates/login/2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="{% url 'login:dashboard' status %}" >
        {% csrf_token %}
        code2: <input type="text" name="code2">
        <br>
        <button type="submit">Next</button>

    </form>
</body>
</html>

login/templates/login/3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="{% url 'login:dashboard' status %}" >
        {% csrf_token %}
        code3: <input type="text" name="code3">
        <br>
        <button type="submit">Next</button>

    </form>
</body>
</html>

login/templates/login/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

    <p>Welcome to sign up process</p>
    <a href="{% url 'login:dashboard' new_profile.status %}">Proceed Next to Register</a>
</body>
</html>

login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <form method="post" action="{% url 'login:register' %}" >
      {% csrf_token %}
      username: <input type="text" name="username">
      <br>
      password: <input type="password" name="password">
      <br><br>
      <button type="submit">Next</button>
  </form>
</body>
</html>

login/templates/login/profileview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
    <div>
        <h1>Your profile details</h1>
        <p>Username: {{ user.username }}</p>
        <p>Password: {{ user.password }}</p>
        <p>Code1: {{ user.code1 }}</p>
        <p>Code2: {{ user.code2 }}</p>
        <p>Code3: {{ user.code3 }}</p>
        <p>Code4: {{ user.code4 }}</p>
        <p>Code5: {{ user.code5 }}</p>
        <p>Code6: {{ user.code6 }}</p>
    </div>
</body>
</html>